// Generated by Swift version 1.1 (swift-600.0.56.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURL;
@class NSData;
@class NSURLResponse;
@class NSError;
@class NSMutableData;
@class NSMutableURLRequest;
@class NSURLConnection;

SWIFT_CLASS("_TtC10YYHRequest10YYHRequest")
@interface YYHRequest : NSObject <NSURLConnectionDataDelegate>
@property (nonatomic) NSURL * url;
@property (nonatomic, copy) NSString * method;
@property (nonatomic) NSData * body;
@property (nonatomic, copy) NSDictionary * headers;
@property (nonatomic, copy) NSDictionary * parameters;
@property (nonatomic, copy) void (^ completionHandler)(NSURLResponse *, NSData *, NSError *);
@property (nonatomic, copy) NSString * contentType;
@property (nonatomic, copy) NSString * userAgent;
@property (nonatomic) NSURLResponse * response;
@property (nonatomic) NSMutableData * responseData;
- (instancetype)initWithUrl:(NSURL *)url OBJC_DESIGNATED_INITIALIZER;
- (void)loadWithCompletion:(void (^)(NSURLResponse *, NSData *, NSError *))completionHandler;
- (void)loadRequest;
- (NSMutableURLRequest *)urlRequest;
- (NSString *)queryString;
- (void)connection:(NSURLConnection *)_ error:(NSError *)error;
- (void)connection:(NSURLConnection *)_ didReceiveResponse:(NSURLResponse *)response;
- (void)connection:(NSURLConnection *)_ didReceiveData:(NSData *)data;
- (void)connectionDidFinishLoading:(NSURLConnection *)_;
@end

#pragma clang diagnostic pop
